### ISSUE TITLE
Names are not being updated along with the rest of the database

### ISSUE THREAD

**Issue by toadfrommariokart64** [thewca/statistics#107]
the website displays competitor's old names, from way before the latest pull from the database.
for the sake of avoiding unneccessary distress, please fix :(

**Comment by campos20** [comment]
This was fixed by https://github.com/thewca/statistics/pull/112/files#diff-e7fb5d95b30044a96812a65a2d7898c4fe319bd28b7f6dc207b3541c6f957196R52

The issue was that some tables were not being updated. Thank you for pointing that out.
