### ISSUE TITLE
Incorrect sorting in Best Result Not Providing a Podium?

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/statistics#122]
Reported by a user: 
> on this page: https://statistics.worldcubeassociation.org/statistics-list/best-result-not-providing-a-podium?selectedKeys=Average%2C3x3x3+One-Handed
> The sub-10 results are ranked below the 10+ results. (looks like the times are being sorted as strings)

**Comment by campos20** [comment]
Fixed, it will reflex on tomorrow's run
