### ISSUE TITLE
Possible issue with calculation of "longest success streak"

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/statistics#124]
Reported via email: 
> I was looking at the "longest success streak" statistic for 3x3 blindfolded. At 20th place there is Kacper Paweł Dworak from Poland with a streak that has ended at 19, from Cube4funLowLimitsJaroslaw2024 to ZmigrodOpen2024. However, looking at 2020DWOR01's profile I only count a streak of 16. I can't see which 3 solves could have been wrongly counted towards the streak. Do you agree that 19 is wrong and 16 is correct?

**Comment by campos20** [comment]
The issue is that We have competitions starting in the same date

<img width="688" alt="image" src="https://github.com/user-attachments/assets/2530c4be-3cfd-4ca4-9b94-de414dd6fa7a">

Cube4funLowLimitsJaroslaw2024, GLSIII2024, results got mixed one inside the other.
