### ISSUE TITLE
Create "evolution of records" graph

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/statistics#65]
### Preliminary notes
* Links to [Issue 6742](https://github.com/thewca/worldcubeassociation.org/issues/6742) on WCA Website repo
* Please refer to [WCA Statistics 2.0 Transition Overview](https://docs.google.com/document/d/161YkIClOIl_YOwwr68v3VY_Nxkbo0RIKP9RiEFsvnfU/edit?usp=sharing) document for context around this change

## Requirement
One of the things still needed in the transition to Statistics 2.0 is an updated version of the ["Evolution of Records"](https://www.worldcubeassociation.org/results/misc/evolution/) graph. 

Basically, we need to recreate that graph in more modern frameworks (Python/ReactJS) inside this repo.

## Description of task

You will need to complete the following steps:
- [ ] A Python script to extract, generate and organise the source data for the graph 
- [ ] Create a frontend page to host the graph in ReactJS
- [ ] Integrate (ie, link to) the page from the main statistic.worldcubeassociation.org website. 
- [ ] Use research and judgement to decide how best to render the graph on the frontend - I don't know enough to advise on how to do this 

## General Comments

One person doesn't need to do all of this - if you only feel confident to do the Python or React sides of this, feel free to just do those.

Even if its one person doing everything, it is strongly recommended to submit a pull request for each piece of this, so that code review is easier. Please feel free to ask for help if you aren't sure if you're going in the right direction.

**Comment by dunkOnIT** [comment]
## Introduction 

Hi there @campos20 - We haven't met yet, but I must say I'm incredibly impressed and excited by what's going on in this repo!

I'm Duncan, and @gregorbg has recently brought me on to help with project management in the WST. 

One of the things he's said the team is working on is trying to transition to statistics.worldcubeassociation.org (which I've started calling "Statistics 2.0" for ease of reference), with the hope of having it be linked into the WCA website in the next month or so - which I'm seeing as the end of March. 

This issue, and the others I might be creating, are part of an effort to try and create clarity and organisation around the team's path to that transition.

PLEASE let me know if you feel like I'm out of line, missing anything, or overstepping at any point. Ideally I should just be making  your life, and the life of the rest of the team easier!

**Comment by dunkOnIT** [comment]
(also - Gregor said I should create an issue for this. I've done on the assumption that someone else besides Alexandre / Sébastien would be working on it. If that's not the case, obviously feel free to just develop this however you wish - my comments in the original post are just meant to guide a developer new to the project)

**Comment by campos20** [comment]
Hi @dunkOnIT. It's great to have you on board. There's an open PR that fixes this. After it's done, I'll update links in the main website.

**Comment by campos20** [comment]
Closing as it is already available

**Comment by dunkOnIT** [comment]
Thanks! Should have done that myself, but thought it would auto-close once the PR was merged. Still got some learning to do with Github :P
