### ISSUE TITLE
Update website copy/text

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/statistics#68]
_I risk sounding like a bit of an asshole on this one - sorry if I do!_

Some of the text on the website appears to be placeholder text that could be expanded upon (eg, more info could be added to the "About" page), or has phrasing that sounds a bit weird to a native English speaker ("We try always to add new statistics." could be "We're always looking to add new statistics").

I expect the focus here has been on putting together the website and its features, not on making sure everything reads perfectly. But I would suggest that the text is reviewed before the site is made live. 

This is something I would be happy to work on, but would only be available to do so next week.

**Comment by saranshgrover** [comment]
This is a good issue to have the WCT work on the text, as they commonly do this for other parts of our site/socials.

**Comment by campos20** [comment]
Great! I asked for help in the language matter. Hopefully now we can make things better.

**Comment by campos20** [comment]
Closing after https://github.com/thewca/statistics/pull/88
