### ISSUE TITLE
Sum of Ranks not loading on Safari

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/statistics#81]
I've had two reports of Sum of Ranks not loading on Safari - one on iOS, one on Mac.

Don't have much information besides that refreshing doesn't fix it. If you'd like me to ask more detailed questions, let me know what you'd like to find out.

**Comment by campos20** [comment]
> I've had two reports of Sum of Ranks not loading on Safari - one on iOS, one on Mac.
> 
> Don't have much information besides that refreshing doesn't fix it. If you'd like me to ask more detailed questions, let me know what you'd like to find out.

Do you know if they've cleared the cache (maybe cmd+f5)

**Comment by dunkOnIT** [comment]
Just had another report of it not working on Safari - not sure what platform, but I've asked them to clear the cache if they're able and advise the results.

**Comment by campos20** [comment]
I just tested on safari with m1. It works. Maybe it was the [regex that we removed](https://github.com/thewca/statistics/pull/82).
