### ISSUE TITLE
Add redirect parameters on login in statistics service

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/statistics#92]
Redirect parameters should be present on every login. The absence of this makes the entire process a bit more cumbersome and potentially confusing for people who are not used to the platform.

For example, take this process:

    Click on a WCA statistics database query URL
    Login required
    User logs in
    Back to home screen. How do I get to the first screen again?

It is a bit counterintuitive. The same happens for any instance of login.

Originally posted by @GuidoDipietro in https://github.com/thewca/worldcubeassociation.org/issues/6777#issuecomment-1311769349

**Comment by campos20** [comment]
I'm not sure if this is possible of fixing just in the statistics side. The website needs to support redirecting to an arbitrary address (like statistics...org/database and not just statistics...org) I'll run some tests.
